project:
  type: book
  output-dir: docs
  
book:
  title: "Pathway Resource Guide"
  subtitle: "Arts, Humanities, and Communication"
  date: "last-modified"
  date-format: iso
  number-depth: 0
  chapters:
    - index.qmd
    - art-design.qmd
    - communication-studies.qmd
    - drama.qmd
    - english.qmd
    - humanities.qmd
    - music.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    section-numbers: false
    highlight-style: github

reference-location: margin
citation-location: margin

editor: visual

