# Humanities {.unnumbered}

## Career Information and Resources

## Transfer Institution Resources

### Central Washington University

-   [Department of History](https://www.cwu.edu/history/)
    -   Phone: Phone: 509-963-1655, Email: [history\@cwu.edu](mailto:history@cwu.edu)
-   [Department of Philosophy and Religious Studies](https://www.cwu.edu/philosophy/)
    -   Phone: 509-963-1818; Email: [philo\@cwu.edu](mailto:philo@cwu.edu)
-   [Department of World Languages and Culture](http://www.cwu.edu/foreign-language/)
    -   Phone: 509-963-1218; Email: [WLang_Dept\@cwu.edu](mailto:WLang_Dept@cwu.edu)
-   [Africana and Black Studies](https://www.cwu.edu/africana/)
    -   Phone: 509-963-1075; Email: [Africana_and_Black_Studies\@cwu.edu](mailto:Africana_and_Black_Studies@cwu.edu)
-   [Asian Studies](https://www.cwu.edu/asian-studies/)
    -   Phone: 509-963-1290; Email: [Asian_Studies\@cwu.edu](mailto:Asian_Studies@cwu.edu)
-   [El Centro Latino and Latin American Studies](https://www.cwu.edu/latino-latin-american/latino-latin-american)
    -   Phone: 509-963-1853; Email: [cllas\@cwu.edu](mailto:cllas@cwu.edu), or Dra. Christina Torres Garcia, Director ([christina.garcia\@cwu.edu](mailto:christina.garcia@cwu.edu))
-   [Liberal Studies](https://www.cwu.edu/arts/liberal-studies-program)
    -   Phone: 509-963-1858; Email: [CAH.Dean\@cwu.edu](mailto:CAH.Dean@cwu.edu)

### Eastern Washington University

### The Evergreen State College

### Portland State University

### University of Washington

### Warner Pacific College

### Washington State University

### Western Washington University
